### ISSUE TITLE
Help running refact tests

### ISSUE THREAD

**Issue by shayne-fletcher** [ndmitchell/hlint#1045]
Not really an HLint issue but I'm hoping you can help @zliu41? As of yesterday, the HLint test suite skips the refact tests advising that my refact exe is too old and I need to get a new one. I'm a bit stuck on how to do that - I even went so far as to clone git@github.com:mpickering/apply-refact.git and `stack build` but even that doesn't seem to have a valid build plan. Do you have any advice?

**Comment by zliu41** [comment]
Yeah HLint now requires apply-refact >= 0.7.0.0 because it relies on passing extensions to apply-refact via `-X` which is supported as of 0.7.0.0.

If you have GHC 8.10 you can just do `cabal install apply-refact`, or if you don't: `nix-shell -p 'haskell.packages.ghc8101.ghcWithPackages (ps: with ps; [])' --run "cabal install apply-refact"` 

Or you can install from nix directly: `nix-env -iA nixpkgs.haskellPackages.apply-refact`

You can also clone the repo and run `cabal install`.

Stack build no longer works because the required version of ghc-exactprint isn't on stackage.

I'm hoping to release a new version soon that supports more GHC versions which hopefully makes it easier.

**Comment by shayne-fletcher** [comment]
> If you have GHC 8.10 you can just do cabal install apply-refact,

That did it for me. 

> Stack build no longer works because the required version of ghc-exactprint isn't on stackage.

Perhaps temporarily the `stack.yaml` could be patched to go to the ghc-exactprint repo-commit-and-sha?

> I'm hoping to release a new version soon that supports more GHC versions which hopefully makes it easier.

Most excellent. Thank-you!

**Comment by zliu41** [comment]
> Perhaps temporarily the stack.yaml could be patched to go to the ghc-exactprint repo-commit-and-sha?

Sounds like a plan!

**Comment by shayne-fletcher** [comment]
> > Perhaps temporarily the stack.yaml could be patched to go to the ghc-exactprint repo-commit-and-sha?
> 
> Sounds like a plan!

Well, I don't know the right thing to do exactly in this instance but it's a shame it doesn't build out of the box 😉  Anyway, I'm working again so pay me no heed!
