### ISSUE TITLE
Automatic eta-reduced forms don't work with operators

### ISSUE THREAD

**Issue by josephcsible** [ndmitchell/hlint#1052]
For hints like `{lhs: concat (map f x), rhs: concatMap f x}`, hlint also automatically matches the eta-reduced version: `concat . map f` will suggest `concatMap f`. Commit 713832f brought to light that this doesn't work right when operators are involved. In particular, `map (fromMaybe False) xs` used to suggest `map (Just True ==) xs`, but now that the hint is the eta-expanded `{lhs: fromMaybe False x, rhs: Just True == x}`, I no longer get that suggestion.

**Comment by ndmitchell** [comment]
I don't see the connection to operators? If you wrote `concatMap f x` becomes `traverse f x`, that also wouldn't apply to `map (concatMap f)` since we don't eta-reduce normal functions as if you wanted them to apply to the eta-reduced form you are expected to do it manually. The fact it doesn't work with the eta-reduction was from #970, and was a deliberate decision, because it was felt that the eta-reduced form was confusing rather than helpful.

**Comment by josephcsible** [comment]
Fair enough.
