### ISSUE TITLE
Error thrown on CPP in the `base` codebase

### ISSUE THREAD

**Issue by Kleidukos** [ndmitchell/hlint#1075]
* Version: `HLint v3.1.6, (C) Neil Mitchell 2006-2020`
* OS: Fedora 32
* Command line: `$ hlint -j --cpp-include="./libraries/base/include/" --cpp-include=includes --cpp-include=./_build/stage1/lib/ -h libraries/base/.hlint.yaml libraries/base`
* Error message:
```
hlint: # error Unknown mingw32 arch
in libraries/base/GHC/Windows.hs  at line 81 col 1
CallStack (from HasCallStack):
  error, called at ./Language/Preprocessor/Cpphs/CppIfdef.hs:113:21 in
  cpphs-1.20.8-DevT7HkEKU3DDQgUoHVnJY:Language.Preprocessor.Cpphs.CppIfdef
```

The CPP code block is :

```c
#if defined(i386_HOST_ARCH)     
# define WINDOWS_CCONV stdcall  
#elif defined(x86_64_HOST_ARCH) 
# define WINDOWS_CCONV ccall    
#else                           
# error Unknown mingw32 arch    
#endif                          
```

**Comment by shayne-fletcher** [comment]
Perhaps adding `--cpp-define x86_64_HOST_ARCH` to the hlint invocation will help here?

**Comment by Kleidukos** [comment]
Perfect! I still get a rather peculiar message from hlint, but other than that, no problem whatsoever!

```
Warning: unknown directive #-}
in libraries/base/Unsafe/Coerce.hs  at line 311 col 1
No hints
```
This is the file in question: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/Unsafe/Coerce.hs#L303-311

**Comment by shayne-fletcher** [comment]
> Perfect! I still get a rather peculiar message from hlint, but other than that, no problem whatsoever!

Awesome.

> ```
> Warning: unknown directive #-}
> in libraries/base/Unsafe/Coerce.hs  at line 311 col 1
> No hints
> ```
> 
> This is the file in question: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/Unsafe/Coerce.hs#L303-311

Ha. That's a genuine problem. The C-preprocessor is being run over the file and it doesn't know what to make of a line that reads,
```
#-}
```
and that's where the warning is coming from. This is because the C-preprocessor interprets lines beginning with a `#` as being those with directives meant for it. Putting a space in front of the leading `#` will fix it.

If this were purely a language extension issue then potential fixes would include:
  - Add `{-# LANGUAGE NoCPP #-}` to the extensions;
  - Pass `-XNoCPP` to hlint so that the extension is disabled by default.

However, I'm not sure in this instance those things alone will do. I don't know if/how HLint can be told to not run CPP in general. @ndmitchell can you advise please?

**Comment by Kleidukos** [comment]
@shayne-fletcher Thanks for the fix! I'll be sure to document the hows and whys on the GHC side.
Cheers!

**Comment by ndmitchell** [comment]
`-XNoCpp` turns off CPP entirely, `--cpp-simple` just strips lines with a leading `#` but otherwise ignores CPP markup. But in this case, with complex CPP, passing a valid set of CPP options as Shayne suggests is the right thing to do.
