### ISSUE TITLE
Lint suggestion: warn on multiple unqualified/exhaustive imports

### ISSUE THREAD

**Issue by joelmccracken** [ndmitchell/hlint#1117]
Something that I encountered in PureScript that I really liked is that it will warn you if you have multiple "exhaustive" imports (im sure there is a better term for this, but I don't know it). 

For example, you would get a warning for:

```
import Prelude
import Foo
```

but you could change it to:

```
import Prelude
import qualified Foo
```

or 

```
import Prelude
import Foo (bar, baz)
```

This ends up making projects a lot nicer to work with, as its easy to see where various imports come from.

**Comment by ndmitchell** [comment]
Thanks for the idea @joelmccracken - however, I have two concerns:

1. I don't like this style. It definitely isn't universal. So it could only ever be at most an opt-in default-off hint.
2. There's no easy way to suggest a replacement from a non-exhaustive style, since HLint doesn't have enough information.

While I'd probably take a simple patch, off-by-default hints don't tend to get much usage. You might be better off looking at [Ghcide](https://github.com/haskell/ghcide), the IDE, which has utilities to show imports with what comes from where, and to change them to be fully explicit, and could certainly gain the action to make an import explicit as a refactoring option. In that situation it has all the information and being an editor has a lot larger surface area to suggest/hint at more things.

**Comment by joelmccracken** [comment]
Gotcha; I’ll do that. Thanks!
