### ISSUE TITLE
Warn on redundant parentheses in (foo . bar) %~ (hello . world)

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#1159]
I was surprised to see that `hlint` doesn't suggest to turn `(foo . bar) %~ (hello . world)` into `foo . bar %~ hello . world`.

I don't know why it doesn't, from reading the code it seems that it should be aware of the fixites of both `%~` and `.`

**Comment by yairchu** [comment]
Checked if this is a regression, but it doesn't seem so. When lens fixities were added in d3d03781b89a5467c7e68560c7649924e5c212e7 it also didn't warn on this

**Comment by ndmitchell** [comment]
HLint deliberately never suggests removing brackets where only fixities mean they aren't required. Taking an easier example, given `a + b * c` I consider whether to put in brackets as `a +(b * c)` as a personal choice, and not something that HLint should either require or remove. It's possible to write a rule to do it if you believe the are specific cases where they shouldn't be used - matching on brackets works, albeit can be a bit tricky to get right because often they are dealt with implicitly.

**Comment by yairchu** [comment]
Oh. What do you think about an option to suggest removing those brackets? I have a feeling that many folks would like such an option (me being one of them).

**Comment by ndmitchell** [comment]
Sure, go for it. Although be aware that HLint sometimes (regularly?) approximates the fixities, and has a few heuristics in a few places to avoid applying "correct" rules because it has low confidence in the parse tree. That might mean the hint is fairly unreliable.

**Comment by yairchu** [comment]
I have an incomplete implementation at https://github.com/ndmitchell/hlint/compare/master...yairchu:brackets which I now use :)

In my branch it's currently always enabled, I guess that to make it optional
ideally it would act as if it's a different type of warning, maybe "Redundant bracket - pedantic"?
Then you could enable/disable the specific hint?
That would probably require `needBracket` to return which type of bracket is necessary (ie `NoBracket | OptionalBracket | NeedBracket`)

**Comment by ndmitchell** [comment]
Looks super cool. Yep, a different name is essential - "Redundant brackets due to fixity"? "Redundant brackets in infix expression"?

I'd suggest creating a separate needBracketFixities - the functions don't overlap that much, so I'd call needBracket to emit a redundant bracket warning, and if that doesn't fire, call needBracketFixities and see if you omit one.

**Comment by yairchu** [comment]
Made it a separate, ignored by default, hint now! Will make a PR after https://github.com/ndmitchell/hlint/pull/1173 which prepares for it

**Comment by ndmitchell** [comment]
Anything else to do here?

**Comment by yairchu** [comment]
Works great! I found that I have plenty of cases of redundant brackets in my code (https://github.com/lamdu/lamdu/commit/b3617059e1cad1163878804e8d34540c4c522f37), and I like removing them because:

* OCD I guess
* Code's more readable without them it seems
* It teaches me about the actually well-designed fixities in lens

🎉

**Comment by ndmitchell** [comment]
Yep, I can see the attraction - thanks for the contribution! I'll highlight it in the next release announcement. Let me know if you'd like me to do a release just for this, otherwise I'll probably accumulate a few more things.

**Comment by yairchu** [comment]
It can wait for the release, I'm already using it from HEAD so no rush :) thanks!

**Comment by ndmitchell** [comment]
Released now :)
