### ISSUE TITLE
Convert changelogs to markdown

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/hlint#129]
This is really an issue with all of your Hackage libraries, but I figured this would be as good of a place as an any to report it.

Hackage was changed recently to support rendering markdown files for `README`s and changelog files, which had the unfortunately side-effect that many existing files now look pretty unreadable on Hackage. A good example is HLint's [changelog](http://hackage.haskell.org/package/hlint-1.9.20/changelog).

Can you convert your changelogs to markdown to fix this?

**Comment by ndmitchell** [comment]
I'm a little reluctant to do that. The files end with `.txt` and Hackage seems to have gone nuts and decided thats the universal convention for Markdown... I find the text file ensures I keep the changelog crisp (I limit it to 70 characters per line) and complete (because each individual entry is small, I can include everything). In contrast, Markdown is going to require me changing everything to bullets or something. Can we get Hackage fixed?

**Comment by ndmitchell** [comment]
I was aware, https://twitter.com/ndm_haskell/status/601052144377176066, but thanks for mentioning it anyway - I was just intending to sit and be a bit bitter, but I should probably try and report it somewhere.

**Comment by RyanGlScott** [comment]
Oops, I didn't think to check the Twitterverse first. :)

In that case, I'll close this issue. Can you reopen it at the [`hackage-server` issue tracker](https://github.com/haskell/hackage-server/issues)? I imagine you'd be more successful in convincing them to change Hackage than I would.

**Comment by ndmitchell** [comment]
Done: https://github.com/haskell/hackage-server/issues/363 - thanks for the prod.
