### ISSUE TITLE
Parse error on UTF-8 with BOM (byte order mark)

### ISSUE THREAD

**Issue by KeesBleijenberg** [ndmitchell/hlint#130]
I'am using Notepad++ as editor on Windows 7 64 bits. If I save a sourcefile as UTF-8 and I run hlint on that source file I get:
hulpfunc:1:1 : Warning: Parse Error: Illegal character ''\65279''.... 
If I convert the file in Notepad++ to UTF-8 without BOM (byte order mark), hlint doesn't complain anymore. It looks like hlint can't handle the BOM that Notepad++ inserts in UTF-8.
I use Hlint version 1.9.20 and ghc version 7.8.3.
BTW why is it a warning? For me (a user) this is a error. I think of a warning as something supicious that you can ignore if you know what you are doing. This problem you can't ignore.

Kees

**Comment by ndmitchell** [comment]
Done, and released as HLint 1.9.21.

Not being able to parse the file is an error for a compiler, of course, and I assume all code going through HLint at least compiles. Therefore any HLint parse error is due to the code not working with HLint, say because of missing preprocessor defines, limitations in the HLint parser etc. As a result, it's a warning, because it's not a style warning. You can certainly argue both ways though.
