### ISSUE TITLE
[Suggestion] Only show certain hints when the respective extensions are enabled

### ISSUE THREAD

**Issue by konsumlamm** [ndmitchell/hlint#1305]
Some hints (like `Use tuple-section` or `Use lambda-case`) suggest changes that require an extension.
I'm not sure if it's doable, but I think it would be nice to only show these hints when the respective extensions are already enabled (or at least add a config option for that).

**Comment by ndmitchell** [comment]
HLint has a rough idea if these extensions are enabled, since it suggests a hint about adding these extensions only if it isn't set.

However, I'm not sure this approach matches the general approach of Haskell developers. Most projects enable many extensions. Adding a new extension isn't considered a big deal. Many projects put the extensions related with those hints in their .cabal file, so they are always on, but in a way HLint can't see. I can certainly believe people don't want tuple-sections, which is why they can be ignored in the normal way, but I'm not sure I suspect that Haskell programmers wouldn't use it to avoid an extension.

**Comment by konsumlamm** [comment]
Those are valid points, just disabling the hints work good enough for me.
