### ISSUE TITLE
Consider defaulting to ghc-lib

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/hlint#1376]
The Cabal flag `ghc-lib` currently defaults to False. Consider changing the default value to True so that projects like HLS that depend on `hlint` can have a working `cabal install ...` command across all GHC versions.

**Comment by ndmitchell** [comment]
There were two reasons for doing it that way:

* For compatible GHC versions, it allows HLS to pass the AST from GHC along without modification, which means less memory, less parsing time, and great compatibility. Is that no longer desired? Or do you have ways to get those advantages without using the same one as the GHC API?
* It makes it slower to compile for users - quite significantly slower. But if it's easier for HLS users, that's probably a worthwhile tradeoff, given there are provided binaries.

**Comment by pepeiborra** [comment]
> There were two reasons for doing it that way:
> 
> 
> 
> * For compatible GHC versions, it allows HLS to pass the AST from GHC along without modification, which means less memory, less parsing time, and great compatibility. Is that no longer desired? 

Less memory and parsing time, yes, but why do you say greater compatibility? 

> Or do you have ways to get those advantages without using the same one as the GHC API?

No, but we are willing to give them up in exchange for greater compatibility. Manual Cabal flags have a poor user interface, specially in combination with Hackage. 

> * It makes it slower to compile for users - quite significantly slower. But if it's easier for HLS users, that's probably a worthwhile tradeoff, given there are provided binaries.

Ah, this is a good point. 

Summarising, HLS really wants to depend on the ghc-lib version of hlint, because that one works on all ghc versions and HLS already depends on ghc-lib anyway. Or as we do now, selectively use the ghc-lib hlint on non-native ghc versions, but in a declarative way. 

I can see how defaulting the flag to true would be a net loss for standalone hlint use cases. 

It occurs to me that the best solution would be a separate package hlint-ghclib.

**Comment by ndmitchell** [comment]
> but why do you say greater compatibility?

You get a AST out of GHC, that must have had all the right CPP, extensions etc set, because you are using it for compilation. The worry is that when HLS tries to create a second GHC AST, it might get some things wrong. This is a worry, but one careful coding can get around.

> No, but we are willing to give them up in exchange for greater compatibility. 

Cool, that sounds a reasonable trade-off to make.

> Manual Cabal flags have a poor user interface, specially in combination with Hackage.

Agreed!

As to how to proceed, moving to ghc-lib by default will slow down compilation times for GHC 9.2.2 users, but in every other way makes things simpler. Two packages would be a bit of a pain, probably not worth the hassle. So it sounds like default to ghc-lib is reasonable and better for HLS.

CC @shayne-fletcher - is there anything you can think that would go wrong if we defaulted to ghc-lib? I know there are some upstream ghc-lib flags that we have to adjust to make things compatible sometimes, but don't think any impact here?

**Comment by shayne-fletcher** [comment]
i think this is a reasonable change and would not object to us making it.

**Comment by shayne-fletcher** [comment]
see also https://github.com/shayne-fletcher/ghc-lib-parser-ex/issues/106#issuecomment-1002805086. @phadej  would you view this change positively too?

**Comment by shayne-fletcher** [comment]
@pepeiborra @ndmitchell  are we agreed on this?

if you indicate consent i propose to release a major version of ghc-lib-parser-ex with the change and following that send a PR to hlint to use it.

**Comment by ndmitchell** [comment]
Sounds good - go for it!

**Comment by ndmitchell** [comment]
So I see we have both #1385 (flipping the default to True) and #1378 (adding a subcomponent). @pepeiborra - does the subcomponent make it easier for HSE, even if we just flip the default to always be True? Are there other benefits it provides, or is this an either/or solution? And if it's a choice, which would you prefer?

**Comment by pepeiborra** [comment]
The sub component works equally well for HSE (assuming we can work out the syntax to use it). 
The main benefit of the sub component approach is preserving the existing hlint binary that does not use ghc-lib.
But there are downsides too, they are not handled well by stack repl: https://github.com/commercialhaskell/stack/issues/4564

**Comment by pepeiborra** [comment]
If we flip the default value to yes ghc-lib, then the sub component adds nothing for HLS

**Comment by ndmitchell** [comment]
Given that new Cabal features tend to have fallout no one can expect (I've been burnt before) I'm inclined to move to ghc-lib on all versions. But alas, that will require waiting for GHC 9.2.3 to have been out a bit longer (a few things still default to 9.2.2) as the Mac build otherwise breaks. I'm envisaging about a month. I guess given we've lived with the issue for a long time, another month seems ok?

**Comment by lf-** [comment]
I found one such bug: https://github.com/haskell/haskell-language-server/issues/3095

**Comment by shayne-fletcher** [comment]
fixed via https://github.com/ndmitchell/hlint/pull/1410

**Comment by shayne-fletcher** [comment]
> I found one such bug: [haskell/haskell-language-server#3095](https://github.com/haskell/haskell-language-server/issues/3095)

hi @lf- could you clarify please? what is meant by "one such bug"?

**Comment by lf-** [comment]
Sorry, I was unclear. I meant a bug related to reparsing the files in hlint with different flags compared to how they were parsed in hls.
