### ISSUE TITLE
hlint needs to ignore bang patterns on pattern matches for # stuff

### ISSUE THREAD

**Issue by bitemyapp** [ndmitchell/hlint#213]
![screenshot from 2016-01-26 00-20-24](https://cloud.githubusercontent.com/assets/320177/12585681/b06dbd16-c412-11e5-9bee-bc060a61b4fc.png)
![screenshot from 2016-01-26 00-20-19](https://cloud.githubusercontent.com/assets/320177/12585688/b5347722-c412-11e5-805a-9e0de2f89760.png)

**Comment by ndmitchell** [comment]
Note that currently if you apply the hint then GHC won't compile the result, so a serious bug. Thanks for the ticket.

**Comment by bitemyapp** [comment]
@ndmitchell yeah sure I'm happy to do dumb things in service of the wider community.

This code was totally unnecessary, GHC was already generating the loop I wanted but I didn't check the Core because I'm a dummy.

**Comment by ndmitchell** [comment]
In fact, the issue is a bit more general than just `#` types - the hint is wrong for all let/where bound patterns (in HSE syntax, those in a `Binds`). HLint also warns about `let !(Just _) = Nothing in ...` which is entirely different from the bang-pattern-less variant. So solution is to find the pat, then walk up the tree and figure out where it is. That's quite a bit harder than what we were doing before.

**Comment by ndmitchell** [comment]
Done.

**Comment by bitemyapp** [comment]
@ndmitchell thank you sir :)
