### ISSUE TITLE
Incorrect suggestion to remove brackets when using type constructors with dots

### ISSUE THREAD

**Issue by m4lvin** [ndmitchell/hlint#247]
data Foo = Foo String deriving (Show)
    main = print $ map (Foo.(show)) [1..5]

Here HLint (v1.9.35) suggests to remove the inner brackets around `show` but then GHC no longer reads `Foo` as a type constructor and tells me that `Foo.show` is not in scope. Similarly `map ((Foo).show) [1..5]` works but HLint wants to remove brackets around `Foo`.

**Comment by ndmitchell** [comment]
I would say that in both cases you should be writing `(Foo . show)` rather than `((Foo).show)` or `(Foo.(show))`. I had never thought of people using brackets to disambiguate the two. So I guess HLint really should be suggesting you drop the brackets, it just isn't triggering that you should be adding the space.

Unfortunately I don't think there's much HLint can do. It works at the level of parse tree - it gets a parse tree and figures out the suggestions on that. It can't tell that your parse tree is very whitespace dependent in this particular case.

**Comment by m4lvin** [comment]
Thanks! I did not know this whitespace dependency.
