### ISSUE TITLE
Ambiguous occurrence of isWindows

### ISSUE THREAD

**Issue by imalsogreg** [ndmitchell/hlint#252]
I've hit some bad combination of `extra` and another library (can't figure out which).

```
src/CmdLine.hs:69:12:
    Ambiguous occurrence ‘isWindows’
    It could refer to either ‘System.FilePath.isWindows’,
                             imported from ‘System.FilePath’ at src/CmdLine.hs:13:1-22
                             (and originally defined in ‘System.FilePath.Current’)
                          or ‘System.Info.Extra.isWindows’,
                             imported from ‘System.Info.Extra’ at src/CmdLine.hs:20:1-24
```

I can send a PR, but does it matter which `isWindows` is used, and which is hidden?

**Comment by ndmitchell** [comment]
The above error suggests `System.FilePath` is exposing `isWindows`. As it happens, I am the maintainer of the `filepath` library, and I know it doesn't expose that - but does happen to define it internally. It also suggests its coming from `System.FilePath.Current`, which the `filepath` package doesn't include.

So how has your system ended up with `isWindows` from `System.FilePath`? If you run:

```
ghc-pkg describe '*' | grep System.FilePath.Current
```

What does it say? Have you tried hacking your filepath library yourself? Are you using Stack or Cabal?

**Comment by imalsogreg** [comment]
Thanks for the quick response. I'm using someone else's wrapper around nix-shell and have a large number of dependencies - so I'm pretty blind to the reasons particular versions of dependencies are being picked. Will keep trying...

**Comment by imalsogreg** [comment]
Ahh - this looks relevant: https://github.com/haskell/filepath/issues/13

**Comment by ndmitchell** [comment]
That issue isn't one that has been changed - unless whoever is giving you the nix-shell is also hot patching filepath at the same time. I consider this a peculiarity of your build script, rather than anything to do with extra or hlint. You may find this script causes other issues, but I'd wait until they arise before investigating further.

**Comment by rimmington** [comment]
I ran into this problem using GHCJS. I've opened a bug: https://github.com/ghcjs/ghcjs-boot/issues/38

**Comment by ndmitchell** [comment]
Thanks @rimmington for opening the upstream ticket. Since it has now happened to two people, and because avoiding it is quite easy, I've done so. However, I still think GHCJS is definitely in the wrong to add extra functions into standard modules, and I won't be testing it, so it may break again in the future.
