### ISSUE TITLE
Suggestion: implement suggestions for liftA and liftM

### ISSUE THREAD

**Issue by Alok** [ndmitchell/hlint#284]
A common (at least for me) case seems to be something like this:

`z = f <$> x <*> y`

which  is equivalent to

`z = liftA2 f x y`

and which reads better, at least in my opinion.  The same could be done for `liftA`-`liftA5`, and `liftM2`-`liftM5`.

Also, using `liftA` does not cause `hlint` to suggest `fmap` instead, but using `liftM` does. I think they should both be warned against.

**Comment by ndmitchell** [comment]
I think that sometimes `liftA2` is better, and sometimes not - I personally tend to prefer the `<*>` variant myself, since it is inductive (adding a new item just follows the pattern) while `liftA2` isn't. You can certainly define it in your own hlint, but it isn't universally liked enough to be in the default.

Good catch on `liftA ==> fmap` though. I've added it.
