### ISSUE TITLE
Suggestion to evaluate const breaks code with type annotations

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#298]
HLint suggests changing this code (which typechecks)

```haskell
ignoringIOErrors :: MonadCatch m => m () -> m ()
ignoringIOErrors ioe = ioe `Exception.catch` (\e -> const (return ()) (e :: IOError))
```

into this (which doesn't).

```haskell
ignoringIOErrors :: MonadCatch m => m () -> m ()
ignoringIOErrors ioe = ioe `Exception.catch` (\e -> (return ()))
```

There might be a more subtle solution, but perhaps HLint could start by not suggesting removing code with type annotations in.

**Comment by ndmitchell** [comment]
I thought about how to avoid this, and even went as far as implementing it and testing it. However, on reflection, I think this just might be something HLint shouldn't even warn about, but potentially should make the list of known breakages at the start of the manual in https://github.com/ndmitchell/hlint#bugs-and-limitations. The only sensible solution to this problem is to use scoped type variables and `(\(e :: IOException) -> ...)`. Putting unused things in a `const` which bind the type is certainly possible - but once you allow that, it's more than just type signatures, for example:

    \e -> const (return ()) (asTypeOf e myIOException)

**Comment by expipiplus1** [comment]
That sounds very reasonable.

I was actually a little surprised that hlint didn't try to correct ` (\(e :: IOError) -> pure ())` to `const (pure ())`!

**Comment by ndmitchell** [comment]
I've modified the readme to generalise to saying certain transformations will require more type signatures.

**Comment by expipiplus1** [comment]
Great, thanks.

**Comment by expipiplus1** [comment]
Or better yet (in this case) `catchIOError`.
