### ISSUE TITLE
HLint incorrectly suggests to "use section" with unary infix operators

### ISSUE THREAD

**Issue by doersino** [ndmitchell/hlint#336]
Given the code snippet

```haskell
(⚑) :: String -> String
(⚑) s = s ++ " world"

main = putStrLn ((⚑) "hello")
```

HLint suggests the following:

```
test.hs:4:17: Suggestion: Use section
Found:
  ((⚑) "hello")
Why not:
  ("hello" ⚑)
```

However, GHC isn't too happy with this replacement:

```haskell
test.hs:7:1: error:
    parse error (possibly incorrect indentation or mismatched brackets)
```

Notably, HLint has no suggestions to offer when the parentheses are removed in favor of `$`:

```haskell
main = putStrLn $ (⚑) "hello"
```

**Comment by ndmitchell** [comment]
Note the use of Unicode is unnecessary to trigger this bug, it also happens with:

```haskell
(%%%) :: String -> String
(%%%) s = s ++ " world"

main = putStrLn ((%%%) "hello")
```

The problem here is that you are using an infix operator which only takes one argument, which is very uncommon. In this case you can enable GHC to work with operator sections by turning on the extension `{-# LANGUAGE PostfixOperators #-}`. What was the use case that caused you to look at a 1-arity operator?

**Comment by doersino** [comment]
Thank you for pointing me to the `PostfixOperators` extension!

The use case was really just to use an unicode symbol as a function name -- it's obviously not essential but makes things a bit clearer in the project I'm working on.

**Comment by ndmitchell** [comment]
So it's more an accident that it comes across as an operator, and you'd probably prefer it just as a name?

**Comment by doersino** [comment]
Yes, this was a workaround for Haskell not allowing Unicode symbols in names.

**Comment by ndmitchell** [comment]
Given you are having a workaround anyway, my temptation is to say use the language extension and that's a consequence of slightly abusing infix operators anyway.
