### ISSUE TITLE
Suggest intCast as a replacement for fromIntegral

### ISSUE THREAD

**Issue by peti** [ndmitchell/hlint#390]
I just learned about `intCast` from http://hackage.haskell.org/package/int-cast-0.1.2.0/docs/Data-IntCast.html, and I would love to have an hlint warning that suggests use of that function instead of `fromIntegral`, which can give quite surprising results due to overflow errors. Is that feasible?

**Comment by ndmitchell** [comment]
`intCast` seems a quite complex solution to something that should be a little bit simpler... I can see the use however, but it's not popular/common enough to justify hlint recommending it by default. It would also have to be making `fromIntegral` banned, since given merely `fromIntegral` I don't know which `intCast` to recommend. I suggest if you want it to avoid `fromIntegral` you add it as a restricted function, like `unsafePerformIO` in this example: https://github.com/ndmitchell/hlint/blob/master/data/default.yaml
