### ISSUE TITLE
Suggesting "optional p" from "option Nothing (Just <$> p)"

### ISSUE THREAD

**Issue by contivero** [ndmitchell/hlint#398]
In my case [option](https://hackage.haskell.org/package/attoparsec-0.13.2.0/docs/Data-Attoparsec-Text.html#v:option) is from attoparsec.

I'm not sure if you want HLint to get into this kind of suggestions, or would rather stick to the base library.
But if it's the former, I guess adding it would require HLint to know that it comes from attoparsec and not other package (other parsers also have `option`, but e.g. Parsec's `option` fails if the parser passed consumes any input at all).

**Comment by ndmitchell** [comment]
There is now an `option` in the base library, so that seems a poor choice in `attoparsec`. However, you can always do `Data.Attoparsec.ByteString.option` and HLint should match through it using what is in scope. There has been some back and forth in #14 about linters for libraries - I suggest if you think it's valuable you add it with the appropriate qualified names and that's fine by me. If the number of hints becomes excessive I can solve that problem later.

**Comment by contivero** [comment]
Which `option` do you mean? [This one](http://hackage.haskell.org/package/base-4.10.0.0/docs/Text-ParserCombinators-ReadP.html#v:option)?
Anyway, I thought it a handy suggestion, but from what I gather from the issue linked, you still aren't sure how to scale adding hints for other libraries.

I could add it to hlint.yaml, qualified, in a section titled `# Attoparsec` with a comment, to avoid mixing it with the other ones. Or we can leave this open until you feel it is appropriate to start adding hints outside base. Your call.

**Comment by ndmitchell** [comment]
Lens hints have been added to the list, in a separate section, so feel free to add it to the standard hlint.yaml file and I'll accept a patch there. I suggest we just add, then when there are too many we refactor, rather than holding up hints based on a refactoring that might never be necessary.
