### ISSUE TITLE
Wish: Check for throw in IO Monad

### ISSUE THREAD

**Issue by pjljvandelaar** [ndmitchell/hlint#497]
On page 150 of  `Parallel and Concurrent Programming in Haskell` by Simon Marlow is written
```
 It is always better to use throwIO rather than throw in the IO
 monad because throwIO guarantees strict ordering with respect to other
 IO operations, whereas throw does not.
```
Could hlint check for the usage of throw within the IO monad?
And even better could it be added to the default checks?

**Comment by ndmitchell** [comment]
Unfortunately not - HLint has no idea whether the monad in question is IO or not, so thus no idea if throwIO would work. It's unfortunate, because I'm a big fan of this hint.

**Comment by ndmitchell** [comment]
Unless of course you can think of a clever way...

**Comment by pjljvandelaar** [comment]
In our case the signature was 'getCPOptsIO :: Maybe FilePath -> IO [Text]' so as a programmer I understood it was within the io monad. Your the expert so if you tell me hlint cannot draw the same conclusion I accept that as a fact.
A petty...

**Comment by ndmitchell** [comment]
That would require finding the type signatures, matching arguments, and basically doing an approximate type inference pass in HLint. So far I've avoided that, because it's very hard to do right, impossible in the file-by-file module HLint operates. If I ever do extend HLint to do that, this will be a hint to add, but for now, unfortunately not possible.

I would however, suggest banning `throw` and having a `throwImpure` or similar so that "short" name people reach for is more likely to be correct.
