### ISSUE TITLE
Support pinning suggestion set to a particular version's set

### ISSUE THREAD

**Issue by slpopejoy** [ndmitchell/hlint#527]
The proposal is to add something to HLint.hs that would set an upper version bound over which suggestions would be automatically suppressed.

The reason is that newer versions of HLint introduce new warnings, which when combined with using CI to enforce HLint, can cause code to start breaking. In our codebase we have instead directly imported HLint into the test suite and made a "HLintSpec" test to run the equivalent of "hlint .". Thus at least a developer will see the breakage by running the test suite locally, before CI.

However, this still however does not address whatever version of hlint a developer might have running on their command line and thus their IDE, resulting in the opposite problem, where some developers are seeing warnings in their IDE that are _not_ enforced by the build system. The version pin would address this part.

**Comment by ndmitchell** [comment]
Your request is to have hlint-2.1.5 have a mode where it only produces the hints that it would have in hlint-2.1.4, so that new hints don't cause problems? Technically testing that would be quite difficult, and there is the problem that sometimes I change utility functions of what variables are called "trivial" or "simple" which has a knock-on impact on lots of hints, changing how they operate.

My preference would be that if you only want hlint-2.1.4 style hints, you just run with that version of hlint, as that is (by construction) guaranteed to give you the right hints. Would there be anything I can do to make it easier to run an old version?

**Comment by ndmitchell** [comment]
Advice to use an old version remains, so that's the solution.
