### ISSUE TITLE
data to newtype with strict field

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hlint#548]
The code

```haskell
data Boo = Boo { boo :: !(Maybe Int) }
```
triggers a suggestion to convert the code to

```haskell
newtype Boo = Boo{boo :: (Maybe Int)}
```
which silently discards the strictness annotation.

This may be related to #285

**Comment by alanz** [comment]
Thanks, that makes sense.

**Comment by thisisrandy** [comment]
I came here thinking I'd found a bug, but the explanation above makes sense. I'll add for posterity that attempting to add a strictness annotation to a `newtype` constructor does not type check (fails with `A newtype constructor cannot have a strictness annotation, but 'Foo’ does`), which makes sense, since `newtype`s are replaced at compile time with their inner type, rendering a strictness annotation meaningless.
