### ISSUE TITLE
Move guards forward confused by NamedFieldPuns

### ISSUE THREAD

**Issue by cblp** [ndmitchell/hlint#745]
(#619 strikes back)

```
Suggestion: Move guards forward
Found:
  [_ | x <- _, let _ = A{x}]
Perhaps:
  [_ | let _ = A{x}, x <- _]
```

With RecodWildCards, it is even worse, because syntactically `A{..}` doesn't use `x`.

**Comment by cblp** [comment]
Also, let binding is not a guard.

**Comment by ndmitchell** [comment]
Thanks for the report. It came while I was on holiday, then fell off the radar somehow. I looked into it and the issue was that for `A{x}` for puns we didn't compute the free variables properly, and moreover, for moving list comprehensions around, we didn't use the free variable computation anyway. Cleaned up now.

As for the naming of the hint, that's a bit of a pain to do, so will leave it for now.
