### ISSUE TITLE
Why do we test refactoring when there are no hints

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#958]
For @zliu41 - I noticed that even if we don't generate any hints, we still test that refactoring preserves the output. Why do we do that? It seems like that isn't testing anything HLint, just the underlying refactor.

Reason I noticed is because https://github.com/ndmitchell/hlint/commit/89d4b656e03f94a6917f5ae1c3e883c1be2ea19b requires a NoRefactor because we don't pass LambdaCase to refactor. But it's a test that we _don't_ generate a hint, so surprised we went that far.

**Comment by zliu41** [comment]
@ndmitchell There's at least one `apply-refact` bug that refactors the code incorrectly (and dangerously)  even if there's no hint (namely, the 3rd case in #499, where -0.5 is changed to 0.5).

You are totally right that this has little to do with HLint, and it should be tested/fixed on the `apply-refact` side. But since HLint has a good number of test cases that generate no hint, it seems reasonable to use them to test `apply-refact` "for free".

I'm OK either way - happy to send a patch to disable refactoring tests when there's no hint!

**Comment by ndmitchell** [comment]
As long as its deliberate I'm less concerned. Essentially they are freebie tests for refactor, which we somewhat critically rely on.
