### ISSUE TITLE
flip is not redundant with BlockArguments 

### ISSUE THREAD

**Issue by Caagr98** [ndmitchell/hlint#979]
It isn't uncommon (for me at least) to write things like `flip Map.traverseWithKey blocks \k v -> do …`, (with BlockArguments for the lambda). In those cases, hlint helpfully points out that this can be changed to `Map.traverseWithKey (\k v -> do …) blocks`, which is certainly not an improvement. In many cases I can insert a `$` to get rid of the suggestion, but that kinda goes against the point of BlockArguments,

**Comment by ndmitchell** [comment]
Agreed - the flip and lambda after is a very natural pattern - we deliberately don't fire flip if there is a `$` in it because it's so common and useful. I've just restricted the `flip` rule further, so it only fires if the final expression is atomic. That won't fire if you are using BlockArguments anymore.
