### ISSUE TITLE
Can I use the HLint API without explicitly depending on `ghc-lib-parser`?

### ISSUE THREAD

**Issue by vaibhavsagar** [ndmitchell/hlint#995]
We've been using [the HLint API in IHaskell](https://github.com/gibiansky/IHaskell/blob/9caa54fdcec71380732037a302037c19a93d9ab8/src/IHaskell/Eval/Lint.hs) and it's been great so far. With the release of HLint 3.0 though, it seems like `SrcLoc` comes from `ghc-lib-parser` unless HLint is compiled against the matching version of GHC. I don't want to incur an explicit dependency on `ghc-lib-parser` because IHaskell also uses the GHC API and I'd rather not use package qualified imports everywhere. My misunderstanding about where `SrcLoc` comes from has already resulted in [this error](https://github.com/commercialhaskell/stackage/pull/5354#issuecomment-627465265), which I can't think of a good way to fix while also maintaining backwards compatibility (we still support GHC 8.0). Can you suggest a way forward? I think that if you re-exported `SrcLoc` then that might fix my particular issue, but I'm not sure if that's a good idea.

**Comment by ndmitchell** [comment]
Sorry this change broke you. For GHC 8.10 we compile against real GHC by default, so for that platform you might want to use a real SrcSpan from GHC.

The `SrcSpan` data type we inherit from GHC is relatively complex, and has an opaque RealSpan inside it. Maybe instead of exporting it, we could expose an unpacking function `unpackSrcLoc :: SrcLoc -> Maybe (FilePath, (Int, Int), (Int, Int))`, and then you can rely on that, which will take you back into the realm of non-GHC data types.

**Comment by vaibhavsagar** [comment]
No need to apologise, HLint is a great project and I'm glad to be able to use it in IHaskell :smile:! That `unpackSrcLoc` change sounds great to me.

**Comment by ndmitchell** [comment]
API added in 4e9f0f0. Let me know if that works, and I'll probably make a release tonight with that in it.

**Comment by vaibhavsagar** [comment]
This works great, thank you! This is the change I made: https://github.com/gibiansky/IHaskell/commit/b8ac6a89a63ebaf5a09147b56c71d6a39e58de98.

**Comment by ndmitchell** [comment]
Released as 3.1.1

**Comment by vaibhavsagar** [comment]
Thank you!
